// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartRoom.BaseDataService.Persistence;

#nullable disable

namespace SmartRoom.BaseDataService.Migrations
{
    [DbContext(typeof(SmartRoomDBContext))]
    [Migration("20220330121303_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartRoom.CommonBase.Core.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("SmartRoom.CommonBase.Core.Entities.RoomEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EquipmentRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomID")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("RoomID");

                    b.ToTable("RoomEquipments");
                });

            modelBuilder.Entity("SmartRoom.CommonBase.Core.Entities.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RoomEquipmentID")
                        .HasColumnType("integer");

                    b.Property<int?>("RoomID")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoomEquipmentID");

                    b.HasIndex("RoomID");

                    b.ToTable("State");

                    b.HasDiscriminator<string>("Discriminator").HasValue("State");
                });

            modelBuilder.Entity("SmartRoom.CommonBase.Core.Entities.BinaryState", b =>
                {
                    b.HasBaseType("SmartRoom.CommonBase.Core.Entities.State");

                    b.Property<bool>("BinaryValue")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("BinaryState");
                });

            modelBuilder.Entity("SmartRoom.CommonBase.Core.Entities.MeasureState", b =>
                {
                    b.HasBaseType("SmartRoom.CommonBase.Core.Entities.State");

                    b.Property<double>("MeasureValue")
                        .HasColumnType("double precision");

                    b.HasDiscriminator().HasValue("MeasureState");
                });

            modelBuilder.Entity("SmartRoom.CommonBase.Core.Entities.RoomEquipment", b =>
                {
                    b.HasOne("SmartRoom.CommonBase.Core.Entities.Room", null)
                        .WithMany("RoomEquipment")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartRoom.CommonBase.Core.Entities.State", b =>
                {
                    b.HasOne("SmartRoom.CommonBase.Core.Entities.RoomEquipment", null)
                        .WithMany("States")
                        .HasForeignKey("RoomEquipmentID");

                    b.HasOne("SmartRoom.CommonBase.Core.Entities.Room", null)
                        .WithMany("State")
                        .HasForeignKey("RoomID");
                });

            modelBuilder.Entity("SmartRoom.CommonBase.Core.Entities.Room", b =>
                {
                    b.Navigation("RoomEquipment");

                    b.Navigation("State");
                });

            modelBuilder.Entity("SmartRoom.CommonBase.Core.Entities.RoomEquipment", b =>
                {
                    b.Navigation("States");
                });
#pragma warning restore 612, 618
        }
    }
}
