version: 2.1
orbs:
  node: circleci/node@4.7.0
  heroku: circleci/heroku@1.2.6
  azure-cli: circleci/azure-cli@1.2.0

jobs:
  # ---------- frontend jobs ----------
  build_and_test_frontend:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./Frontend/smart-home-ui
          pkg-manager: npm
      - run:
          command: cd Frontend/smart-home-ui && npm test
          name: Run tests
      - run:
          command: cd Frontend/smart-home-ui && npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
            
  deploy_frontend: # this can be any name you choose
    docker:
      - image: cimg/node:17.2.0
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true # force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git

  # ---------- backend jobs ----------
  build_and_test_CommonBase:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
          working_directory: Backend/SmartRoom/SmartRoom.CommonBase
      - run:
          name: Build
          command: dotnet build -c Release
          working_directory: Backend/SmartRoom/SmartRoom.CommonBase
      - run:
          name: Running Tests
          command: dotnet test
          working_directory: Backend/SmartRoom/SmartRoom.CommonBase.Tests

  build_and_test_BaseDataService:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
          working_directory: Backend/SmartRoom/SmartRoom.BaseDataService
      - run:
          name: Build
          command: dotnet build -c Release
          working_directory: Backend/SmartRoom/SmartRoom.BaseDataService
      - run:
          name: Running Tests
          command: dotnet test
          working_directory: Backend/SmartRoom/SmartRoom.BaseDataService.Tests
      - run:
          name: Publish
          command: dotnet publish -c Release -o /WebService
          working_directory: Backend/SmartRoom/SmartRoom.BaseDataService
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./Backend

  build_and_test_TransDataService:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
          working_directory: Backend/SmartRoom/SmartRoom.TransDataService
      - run:
          name: Build
          command: dotnet build -c Release
          working_directory: Backend/SmartRoom/SmartRoom.TransDataService
      - run:
          name: Running Tests
          command: dotnet test
          working_directory: Backend/SmartRoom/SmartRoom.TransDataService.Tests
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./Backend

  build_and_test_DataSimulatorService:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
          working_directory: Backend/SmartRoom/SmartRoom.DataSimulatorService
      - run:
          name: Build
          command: dotnet build -c Release
          working_directory: Backend/SmartRoom/SmartRoom.DataSimulatorService
      - run:
          name: Running Tests
          command: dotnet test
          working_directory: Backend/SmartRoom/SmartRoom.DataSimulatorService.Tests
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./Backend

  azure_deploy_backend:
    executor: azure-cli/azure-docker
    steps:
      - azure-cli/login-with-service-principal
      - run:
          command: az webapp deployment source show --resource-group SmartRoom --name BaseDataService
          working_directory: Backend/SmartRoom/SmartRoom.BaseDataService
      - run:
          name: "Deploy Web App to Azure"
          command: |
            az webapp deployment source config-local-git --resource-group SmartRoom --name BaseDataService
            ls
            cd ~/project/Backend/SmartRoom/SmartRoom.BaseDataService
            git init
            git config --global user.email "me@mail.com"
            git config --global user.name "yemiwebby"
            git add . 
            git commit -m "Deployed app"
            git remote add azure https://PublishUser_BaseDataService:fya!wcb.veb.cje5FRE@basedataservice.scm.azurewebsites.net/BaseDataService.git
            git push azure master
          working_directory: Backend/SmartRoom/SmartRoom.BaseDataService

workflows:
  on_commit:
    jobs:
      - build_and_test_CommonBase:
          filters:
            branches:
              only:
                - main
                - /^release_.*/   
                - DataSimulator
      - build_and_test_BaseDataService:
          requires: 
            - build_and_test_CommonBase
          filters:
            branches:
              only:
                - main
                - /^release_.*/
                - DataSimulator
      - build_and_test_TransDataService:
          requires: 
            - build_and_test_CommonBase
          filters:
            branches:
              only:
                - main
                - /^release_.*/
                - DataSimulator 
      - build_and_test_DataSimulatorService:
          requires: 
            - build_and_test_TransDataService
            - build_and_test_BaseDataService
          filters:
            branches:
              only:
                - main
                - /^release_.*/
                - DataSimulator
      - build_and_test_frontend:
          filters:
            branches:
              only:
                - main
                - /^release_.*/
      - azure_deploy_backend:
          requires:
            - build_and_test_DataSimulatorService
